#!/usr/bin/env bash
# verify-handoff.sh — mechanical verify-loop evidence harness (v2.30.0)
#
# WHY THIS EXISTS: small models cannot reliably self-report verify compliance.
# Field traces (2026-07, gpt-5-mini): `|| true` appended to gates, biome errors
# relabeled "non-blocking suggestions", output head-truncated past the summary
# line (`| sed -n '1,240p'` cut off "Found 57 errors"), integration commands
# never run ("covered by the suite"), pass counts below baseline shipped anyway.
# Every one of those was a prose rule the model broke. This script makes them
# mechanical: it runs each command EXACTLY as written, captures full output,
# keeps the TAIL, extracts pass counts, compares against a stored baseline, and
# writes the report itself. The model's job shrinks to: run this, read the one
# verdict line, fix, re-run.
#
# Usage:
#   bash verify-handoff.sh <file>              # run commands from the file's ```verify fence
#   bash verify-handoff.sh <file> --baseline   # also store pass-count baseline (run BEFORE editing)
#   bash verify-handoff.sh -c "cmd" [-c ...]   # explicit commands, no file
#   Options: --report <path>   (default docs/work/VERIFY_REPORT.md)
#
# The ```verify fence: first fenced block opening with ```verify in the file;
# each non-empty, non-# line is one command, run verbatim via `bash -c` from
# the directory this script was invoked in. Exit: 0 = ALL GREEN, 1 = RED,
# 2 = usage/no commands.
#
# Never-sudo, dependency-free (bash 3.2+, awk, tail, grep). Never masks an
# exit code; never truncates the head of a summary.
set -u

FILE=""
BASELINE_MODE=0
REPORT=""
CMDS=()

while [ $# -gt 0 ]; do
  case "$1" in
    --baseline) BASELINE_MODE=1 ;;
    --report)
      [ $# -ge 2 ] || { echo "verify-handoff: --report needs a path" >&2; exit 2; }
      REPORT="$2"; shift ;;
    -c)
      [ $# -ge 2 ] || { echo "verify-handoff: -c needs a command" >&2; exit 2; }
      CMDS+=("$2"); shift ;;
    -h|--help)
      sed -n '2,28p' "$0"; exit 0 ;;
    -*)
      echo "verify-handoff: unknown option $1" >&2; exit 2 ;;
    *)
      FILE="$1" ;;
  esac
  shift
done

ROOT="$(pwd)"

# --- collect commands -------------------------------------------------------
if [ ${#CMDS[@]} -eq 0 ]; then
  if [ -z "$FILE" ]; then
    echo "verify-handoff: pass a file with a \`\`\`verify fence, or -c commands. See --help." >&2
    exit 2
  fi
  if [ ! -f "$FILE" ]; then
    echo "verify-handoff: file not found: $FILE (paths are project-relative)" >&2
    exit 2
  fi
  while IFS= read -r line; do
    case "$line" in
      ''|'#'*) continue ;;
    esac
    CMDS+=("$line")
  done < <(awk '
    done_block == 1        { next }
    /^```verify[[:space:]]*$/ { in_block = 1; next }
    in_block && /^```/     { done_block = 1; next }
    in_block               { print }
  ' "$FILE")
  if [ ${#CMDS[@]} -eq 0 ]; then
    echo "verify-handoff: no \`\`\`verify fence with commands found in $FILE" >&2
    echo "  Add one (each line = one command, run verbatim):" >&2
    printf '  ```verify\n  cd apps/api && npx vitest run\n  ```\n' >&2
    exit 2
  fi
fi

# --- output locations -------------------------------------------------------
if [ -d "docs/work" ]; then OUT="docs/work"; else OUT="."; fi
LOGDIR="$OUT/verify-logs"
mkdir -p "$LOGDIR"
[ -n "$REPORT" ] || REPORT="$OUT/VERIFY_REPORT.md"
BASE_FILE="$OUT/verify-baseline.txt"

# --- auto-baseline -----------------------------------------------------------
# A baseline is only meaningful pre-change. If none is stored, store one
# automatically WHEN we can prove this run is pre-change: clean working tree
# AND the branch has no commits beyond the base branch. Otherwise warn loudly —
# a missing baseline means test deletion cannot be detected mechanically.
if [ "$BASELINE_MODE" -eq 0 ] && [ ! -f "$BASE_FILE" ]; then
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    CLEAN=$(git status --porcelain 2>/dev/null | grep -Ev ' docs/(work|reviews)/' || true)
    BASE_BRANCH=""
    git show-ref --verify --quiet refs/heads/main && BASE_BRANCH="main"
    [ -z "$BASE_BRANCH" ] && git show-ref --verify --quiet refs/heads/master && BASE_BRANCH="master"
    AHEAD=0
    if [ -n "$BASE_BRANCH" ]; then
      AHEAD=$(git log "$BASE_BRANCH"..HEAD --oneline 2>/dev/null | wc -l | tr -d ' ')
    fi
    if [ -z "$CLEAN" ] && [ -n "$BASE_BRANCH" ] && [ "$AHEAD" -eq 0 ]; then
      BASELINE_MODE=1
      echo "note: no baseline stored + clean pre-change tree — storing baseline automatically"
    else
      echo "WARNING: no baseline stored and the tree already has changes — pass-count"
      echo "         regressions CANNOT be detected. If you have not edited yet, commit/stash"
      echo "         and re-run with --baseline from the clean pre-change state." >&2
    fi
  fi
fi

# --- run --------------------------------------------------------------------
STAMP="$(date -u '+%Y-%m-%d %H:%M:%SZ' 2>/dev/null || date)"
{
  echo "# VERIFY REPORT — generated by verify-handoff.sh, not hand-written"
  echo ""
  echo "- Generated: $STAMP"
  echo "- Working dir: $ROOT"
  [ -n "$FILE" ] && echo "- Commands from: $FILE (\`\`\`verify fence)"
  echo "- Full per-command logs: $LOGDIR/NN.log"
  echo ""
} > "$REPORT"

N=0
GREEN=0
RED_CMD=""
RED_CODE=0
TOTAL_PASSED=0

for cmd in "${CMDS[@]}"; do
  N=$((N + 1))
  LOG="$LOGDIR/$(printf '%02d' "$N").log"
  echo "[$N/${#CMDS[@]}] $cmd"
  ( cd "$ROOT" && bash -c "$cmd" ) > "$LOG" 2>&1
  CODE=$?

  # Sum every "<n> passed"/"<n> passing" occurrence (vitest/jest/go styles).
  # The sum is only compared against a baseline produced by the same commands,
  # so double-counting ("Test Files 69 passed" + "Tests 1152 passed") is stable.
  CMD_PASSED=$(grep -Eo '[0-9]+ pass(ed|ing)' "$LOG" 2>/dev/null | grep -Eo '[0-9]+' | awk '{ s += $1 } END { print s + 0 }')
  TOTAL_PASSED=$((TOTAL_PASSED + CMD_PASSED))

  {
    echo "## Command $N"
    echo ""
    echo '```'
    echo "$cmd"
    echo '```'
    echo ""
    echo "- Exit code: **$CODE**"
    [ "$CMD_PASSED" -gt 0 ] && echo "- Pass-count mentions summed: $CMD_PASSED"
    echo "- Output TAIL (last 15 lines — the summary end; full log: $LOG):"
    echo ""
    echo '```'
    tail -n 15 "$LOG"
    echo '```'
    echo ""
  } >> "$REPORT"

  if [ "$CODE" -eq 0 ]; then
    GREEN=$((GREEN + 1))
    echo "    exit 0"
  else
    echo "    exit $CODE  <-- RED"
    if [ -z "$RED_CMD" ]; then RED_CMD="$cmd"; RED_CODE=$CODE; fi
  fi
done

# --- baseline ---------------------------------------------------------------
BASELINE_RED=""
if [ "$BASELINE_MODE" -eq 1 ]; then
  echo "$TOTAL_PASSED" > "$BASE_FILE"
  echo "- Baseline stored: $TOTAL_PASSED summed pass-count ($BASE_FILE)" >> "$REPORT"
  echo "baseline stored: $TOTAL_PASSED"
elif [ -f "$BASE_FILE" ]; then
  BASE=$(tr -cd '0-9' < "$BASE_FILE")
  if [ -n "$BASE" ] && [ "$TOTAL_PASSED" -lt "$BASE" ]; then
    BASELINE_RED="pass-count regressed: $TOTAL_PASSED < baseline $BASE — existing tests were deleted or broken"
  fi
  echo "- Baseline check: current $TOTAL_PASSED vs stored $BASE ${BASELINE_RED:+— REGRESSION}" >> "$REPORT"
fi

# --- verdict ----------------------------------------------------------------
echo "" >> "$REPORT"
if [ -n "$RED_CMD" ]; then
  VERDICT="VERIFY: RED — exit $RED_CODE from: $RED_CMD"
elif [ -n "$BASELINE_RED" ]; then
  VERDICT="VERIFY: RED — $BASELINE_RED"
else
  VERDICT="VERIFY: ALL GREEN ($GREEN/$N)"
fi
echo "**$VERDICT**" >> "$REPORT"
echo "$VERDICT"
echo "report: $REPORT"

case "$VERDICT" in
  "VERIFY: ALL GREEN"*) exit 0 ;;
  *) exit 1 ;;
esac
